### ISSUE TITLE
Upon activation of stripminer the game crashes.

### ISSUE THREAD

**Issue by ArtificialAzur** [Ladysnake/BLAST#13]
Any ideas on what is causing it?

**Comment by ArtificialAzur** [comment]
I've tried to re-open the world too and it crashes immediately.

**Comment by UpcraftLP** [comment]
Got a log?

**Comment by ArtificialAzur** [comment]
I looked at the log but forgot to take ss of it, I had to uninstall the mod anyways so I could load into my world.
