### ISSUE TITLE
Diamond Trigger Bomb

### ISSUE THREAD

**Issue by idontkonwhow** [Ladysnake/BLAST#14]
i throw it in the nether, and game crashes.

here is crash report :

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 3/31/21 10:52 PM
Description: Ticking entity

java.lang.ClassCastException: ladysnake.blast.common.entity.DiamondTriggerBombEntity cannot be cast to net.minecraft.class_1309
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at net.minecraft.loot.function.ApplyBonusLootFunction.handler$zdp000$inject(ApplyBonusLootFunction:532)
	at net.minecraft.loot.function.ApplyBonusLootFunction.process(ApplyBonusLootFunction)
	at net.minecraft.loot.function.ConditionalLootFunction.apply(ConditionalLootFunction:31)
	at net.minecraft.loot.function.ConditionalLootFunction.apply(ConditionalLootFunction:20)
	at net.minecraft.loot.function.LootFunctionTypes.method_591(LootFunctionTypes:54)
	at net.minecraft.loot.function.LootFunction.method_514(LootFunction:14)
	at net.minecraft.loot.entry.ItemEntry.generateLoot(ItemEntry:33)
	at net.minecraft.class_85$1.generateLoot(class_85.java:59)
	at net.minecraft.loot.LootPool.supplyOnce(LootPool:71)
	at net.minecraft.loot.LootPool.addGeneratedLoot(LootPool:95)
	at net.minecraft.loot.LootTable.generateUnprocessedLoot(LootTable:73)
	at net.minecraft.loot.LootTable.generateLoot(LootTable:82)
	at net.minecraft.loot.LootTable.generateLoot(LootTable:87)
	at net.minecraft.block.AbstractBlock.getDroppedStacks(AbstractBlock:249)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.getDroppedStacks(AbstractBlock:890)
	at ladysnake.blast.common.world.CustomExplosion.affectWorld(CustomExplosion.java:225)
	at ladysnake.blast.common.entity.BombEntity.explode(BombEntity.java:93)
	at ladysnake.blast.common.entity.BombEntity.onCollision(BombEntity.java:61)
	at ladysnake.blast.common.entity.TriggerBombEntity.onCollision(TriggerBombEntity.java:42)
	at net.minecraft.entity.projectile.thrown.ThrownEntity.tick(ThrownEntity:67)
	at ladysnake.blast.common.entity.BombEntity.tick(BombEntity.java:72)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
	at net.minecraft.world.World.tickEntity(World:561)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Details:
	Entity Type: blast:diamond_trigger_bomb (ladysnake.blast.common.entity.DiamondTriggerBombEntity)
	Entity ID: 26575
	Entity Name: entity.blast.diamond_trigger_bomb
	Entity's Exact location: -59.83, 17.43, 446.44
	Entity's Block location: World: (-60,17,446), Chunk: (at 4,1,14 in -4,27; contains blocks -64,0,432 to -49,255,447), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {Fuse:40s,Motion:[0.0d,0.0d,0.0d],cpadidTP:0b,Invulnerable:0b,Air:300s,OnGround:0b,PortalCooldown:0,cpacooldown:0,Rotation:[90.230896f,9.022265f],FallDistance:0.0f,Pos:[-59.8278136002254d,17.42998189291618d,446.4366294106401d],Fire:-1s,UUID:[I;497611146,317737907,-2125751400,352718560]}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:564)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)
-- Affected level --
Details:
	All players: 1 total; [class_3222['dude0c'/26288, l='ServerLevel[very new]', x=-71.20, y=14.00, z=446.48]]
	Chunk stats: ServerChunkCache: 1521
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-65,64,207), Chunk: (at 15,4,15 in -5,12; contains blocks -80,0,192 to -65,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1554616 game time, 1792867 day time
	Level name: very new
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 13307 (now: true), thunder time: 26600 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 576415976 bytes (549 MB) / 2949120000 bytes (2812 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms404m -Xmx4096m
	Suspected Mods: BLAST (blast)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.8
		advdebug: Advancements Debug 2.2.0
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anvil_fix: AnvilFix 1.1.3+build.7-1.16
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.10.138
		artifacts: Artifacts 3.1.0+fabric
		attributefix: Attribute Fix {FABRIC} 1.0.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		automated_crafting: Automated Crafting 1.3.21+MC1.16.2-1.16.5
		backpackmod: Backpack Mod 1.16-1.2.3
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.9.1-pre
		betterf3: BetterF3 1.1.2
		betternether: Better Nether 5.0.7
		bigbeacons: Big Beacons 1.0.1
		blast: BLAST 1.5.2
		bno: Basic Nether Ores 1.16.4-5.4.0-Fabric
		boostedbrightness: Boosted Brightness 1.2.0
		bowinfinityfix: Bow Infinity Fix rv9
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		cardinal-components: Cardinal Components API 2.7.13
		cardinal-components-base: Cardinal Components API (base) 2.7.13
		cardinal-components-block: Cardinal Components API (blocks) 2.7.13
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.13
		cardinal-components-entity: Cardinal Components API (entities) 2.7.13
		cardinal-components-item: Cardinal Components API (items) 2.7.13
		cardinal-components-level: Cardinal Components API (world saves) 2.7.13
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.13
		cardinal-components-util: Cardinal Components API (utilities) 2.7.13
		cardinal-components-world: Cardinal Components API (worlds) 2.7.13
		castle_dungeons: Castle Dungeons 2.1-1.16.5-fabric
		cavebiomes: Cave Biomes 0.6.2
		ccrp: Crazy Creepers 1.3.1
		chainmail: Chainmail 0.5.0
		cleancut: CleanCut mc1.16-2.1-fabric
		cleanview: CleanView 1.16.4-v1-fabric
		clear-skies: Clear Skies 1.5.54
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.11.17
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compact-storage: CompactStorage 4.1.0
		compactstatuseffects: Compact Status Effects 1.2.3
		completeconfig: CompleteConfig 0.12.0
		concreteconversion: Concrete Conversion 4.1.0.0
		configspawners: Configurable Spawners 1.0.1
		craftnstar: Craftable nether star 1.0.0
		creeperspores: Creeper Spores 1.5.0
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.12-1.16.5
		customportalapi: customportalapi 0.0.1-beta18-1.16
		dankstorage: Dank Storage 1.9a-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dungeons_of_exile: Dungeons of Exile 1.1.1
		dynamicfps: Dynamic FPS 2.0.1
		easiervillagertrading: EasierVillagerTrading 1.16.4-fabric0.25.1-1.5.3
		economical_villager_trading: Economical Villager Trading 1.2+MC1.16.4-1.16.5
		ecotones: Ecotones 0.7.1
		eldritch_mobs: Eldritch Mobs 1.6.8
		enchant_giver: Enchant Giver 1.0.3
		enhancedcelestials: Enhanced Celestials 1.0.2
		entityculling: EntityCulling-Fabric 1.2.0
		expandedstorage: ExpandedStorage 5.6.33
		extraalchemy: Extra Alchemy 1.3.1
		fabric: Fabric API 0.32.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		falling_tree: FallingTree 2.10.0
		faster-minecarts: Faster Minecarts 1.1.2
		fastfurnace: FastFurnace 2.3
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		flesh2leather: Flesh2Leather 1.0.2
		fluidtank: Fluid Tank 16.1.0-fabric
		flytre_lib: FlytreLib 0.2.7
		ftbguilibrary: FTB GUI Library 1605.2.1.40
		ftbultimine: FTB Ultimine 1605.2.0-build.23
		gobber2: Gobber2 2.3.71
		golemsgalore: Golems Galore 0.2.1+mc.1.16.5
		gottaclimbfast: Gotta Climb Fast! 1.0
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		healthoverlay: Health Overlay 3.6.14
		hplus: Hopper Plus 1.0.10
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		inmis: Inmis 2.0.1-beta-1.16.2
		instantlava: InstantLava 1.2.1
		inventory_control_tweaks: Inventory Control Tweaks 1.3.1+MC1.16.2-1.16.5
		inventoryhud: Inventory HUD + 3.2.2
		inventoryprofiles: Inventory Profiles 0.4.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kibe: Kibe 1.6.5-BETA
		krypton: Krypton 0.1.2
		launchersmod: Launchers 3.2.0
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.8.5
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		library_of_exile: Library of Exile 1.0.6
		lightoverlay: Light Overlay 5.5.4
		lithium: Lithium 0.6.4
		loading-timer: Loading Timer 1.2.2
		magic_lanterns: Magic Lanterns 1.4.5
		magna: Magna 1.5.1-1.16.5
		make-every-biome-spawnable-lol: Make Every Biome Spawnable Makes Every Biome Spawnable 1.16.5-1.0.0
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.5
		mobfarmutilities: Mob Farm Helpers 1.3.0
		modmenu: Mod Menu 1.16.8
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		mousewheelie: Mouse Wheelie 1.6.1+mc1.16.4
		multi_item_lin: Multi Item Lin 1.0.0
		netherite_plus: Netherite Plus Mod 1.3.3-1.16.5
		no_fog: No Fog 1.0.2-beta.1+1.16.2
		nonevaporation: NonEvaporation 1.0.0
		notenoughcrashes: Not Enough Crashes 3.1.8
		notenoughcreativity: Not Enough Creativity 1.2.2
		notenoughmilk: Not Enough Milk 1.1.0
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		oro_config: OroArmor Config -0df99c92b1-1
		patchouli: Patchouli 1.16.4-50-FABRIC
		phosphor: Phosphor 0.7.1+build.11
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.10-1.16.5
		pugh_lib: Pugh Lib 1.1.0
		reborncore: Reborn Core 4.7.2+build.132
		repurposed_structures: Repurposed Structures 1.16.5-1.8.2
		reroll: Reroll 1.2.0-1.16.5
		resourcecrops: Resource Crops 1.0.7
		resourceful_tools: Resourceful Tools 1.0.56
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.11.188
		roughlyenoughitems-api: REI (API) 5.11.188
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.188
		roughlyenoughitems-runtime: REI (Runtime) 5.11.188
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		rpgstats: RPGStats 3.2.6+1.16.5
		satin: Satin 1.6.0-nightly.20w48a
		simple_backpack: SimpleBackpack 1.0.38
		smoothboot: Smooth Boot 1.16-1.3.1
		smootherbedrock: Smoother Bedrock 1.0.0
		sodium: Sodium 0.1.0
		spatialharvesters: Spatial Harvesters 0.11.7a
		staffofbuilding: Staff of Building 1.2.4-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		stoneholm: Stoneholm 1.1.0
		structurized: Structurized 1.2.0-1.16.5
		talltallcane: Tall Tall Cane 1.0
		team_reborn_energy: Energy 0.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.3
		terraform-config-api-v1: Terraform Config API (v1) 1.0.2
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.2
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.2
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.3
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.2
		throwabletorch: ThrowableTorch 1.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torcherino: Torcherino 2.12.69
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		tweakeroo: Tweakeroo 0.10.0-dev.20210118.163914
		tweed: Tweed API 3.0.0-beta.22
		vanilla-hammers: Vanilla Hammers 3.0.2-1.16.5
		vanilladeathchest: VanillaDeathChest 2.0.6-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		voyager: Voyager 1.0.0
		wands: Wands Mod 1.3.1
		woodcutter: Woodcutter 1.2-1.16.1
		worldedit: WorldEdit 7.2.3+5680-135941e
		wthit: wthit 2.5.4
		xaerominimap: Xaero's Minimap 21.4.0
		xaeroworldmap: Xaero's World Map 1.12.0
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['dude0c'/26288, l='ServerLevel[very new]', x=-71.20, y=14.00, z=446.48]]
	Data Packs: vanilla (incompatible), Fabric Mods, file/ichphilipp-s-endcity-v1-1-1-16-2.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 2

**Comment by MoriyaShiine** [comment]
No longer an issue as of 1.13-1.21.1
