### ISSUE TITLE
Blast crashes modpack on startup. 

### ISSUE THREAD

**Issue by toErIpNid** [Ladysnake/BLAST#17]
Blast Version: 1.5.2
MC Version: 1.16.5
Fabric Version: 0.11.6

Log: 
[crash-2021-06-17_13.05.01-server.txt](https://github.com/Ladysnake/BLAST/files/6672365/crash-2021-06-17_13.05.01-server.txt)

**Comment by doctor4t** [comment]
Are you sure it's Blast? You have quite a mod list and the log doesn't make it obvious it is

**Comment by toErIpNid** [comment]
When I disable blast, the modpack works, so it has to have something to do with it.
