### ISSUE TITLE
BLAST items does not respect "GOML" claims

### ISSUE THREAD

**Issue by bd79** [Ladysnake/BLAST#18]
When using the explosives it does not properly check for the claims owner and if they are allowed to use said explosives.

**Comment by doctor4t** [comment]
Fixed on GOML's side on 1.17. I'll also properly set the owner of the bomb soon, cause turns out I wasn't doing that already.
![image](https://user-images.githubusercontent.com/25477005/122621526-22a76680-d096-11eb-97ec-d15642fa078c.png)

**Comment by itsdinkd** [comment]
Nor do they respect FLAN claims. I destroyed a Flan base with the new bombarder (also I thought bombarder is supposed to prevent destruction?)
