### ISSUE TITLE
[1.17] Gunpowder block explosions result in flying fire

### ISSUE THREAD

**Issue by Xiribidus** [Ladysnake/BLAST#19]
Works for single gunpowder blocks as well as multiple ones, seems to generate even on blocks it blows up with its own explosion

**Comment by PsychoBreadstick** [comment]
I guess an easy way to patch this is just make the fire be placed down after the blocks are blown up instead of before. Since it seems that's the problem.

**Comment by Xiribidus** [comment]
Fixed in newer versions
