### ISSUE TITLE
[1.17.1] Stripminer bug

### ISSUE THREAD

**Issue by itsdinkd** [Ladysnake/BLAST#21]
Stripminer is completely bugged. Last 2-3 versions, including latest 1.8.1, if you light a stripminer your game will disconnect from server and will not allow you to join back.

No crash log, nothing in latest log either.

**Comment by netcore10** [comment]
Can confirm I had this problem on 1.20.1, only we can get back into the server every time it boots us. It mentions something about an entity. this is a log of one of my players https://paste.atlauncher.com/view/043551ac-d21d-4f69-9f82-065b0d71cb47

**Comment by MoriyaShiine** [comment]
No longer an issue as of 1.13-1.21.1
