### ISSUE TITLE
Bombarder not respecting FLAN claims

### ISSUE THREAD

**Issue by itsdinkd** [Ladysnake/BLAST#22]
1.8.1 Blast / 1.17.1 / Fabric (latest API)

Two things are happening.

1) Bombarder is being destructive but for some reason only in FLAN claims.
2) It's not respecting FLAN claims and destroying claimed blocks

**Comment by doctor4t** [comment]
You mean the Bombard? But the bombs it throws do not destroy blocks normally. Something must be interferring with the properties of the bomb projectile.

**Comment by itsdinkd** [comment]
the blocks destroyed were as follows;
Blockus Mod: Block of Diamond, Block of Emerald
Expanded Storage: Golden Chest, Diamond Chest

I shot one at a wall, and one at the ceiling. Ceiling one fell down at a perfect vertical angle 

Also thought it was weird because I was using it outside the base with vanilla blocks and it definitely was not destroying. Maybe those blocks have a similar tag to the diamond/gold blocks and the bombs thought it think it was ore?

**Comment by EvieTheOwl** [comment]
This should be fixed in #43
