### ISSUE TITLE
[Feature Request] Config file

### ISSUE THREAD

**Issue by itsdinkd** [Ladysnake/BLAST#23]
Since the new, and upcoming versions are including new bombs, it would be great to have a config file to either disable certain bombs, to enable / disable block destruction, and to modify damage output values. :)

**Comment by doctor4t** [comment]
To disable bombs, you can make a datapack to remove their recipe. I'm not exactly a fan of configurations, as I don't find them fun to make at all.

Regarding the block destruction, I guess I could make a gamerule to control that, but for the damage, it's calculated by the explosion itself, and I'm not exactly keen on making a config just for that.

**Comment by itsdinkd** [comment]
I see, no worries then! Creating datapacks aren’t hard I can do that that’s fine.    From: doctor4tSent: Thursday, September 30, 2021 9:14 AMTo: Ladysnake/BLASTCc: red2blue; AuthorSubject: Re: [Ladysnake/BLAST] [Feature Request] Config file (#23) To disable bombs, you can make a datapack to remove their recipe. I'm not exactly a fan of configurations, as I don't find them fun to make at all.Regarding the block destruction, I guess I could make a gamerule to control that, but for the damage, it's calculated by the explosion itself, and I'm not exactly keen on making a config just for that.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
