### ISSUE TITLE
Rebalancing hand-thrown bombs.

### ISSUE THREAD

**Issue by PsychoBreadstick** [Ladysnake/BLAST#26]
Now, bombards are pretty balanced. High damage, can damage mobs in an area, but slow fire rate. Throwing bombs right from your hand. While doing actual damage to blocks and having a little less range, can be spammed to extreme measures. Allowing for pretty insane dps. On top of more powerful hand-thrown bombs like diamond and naval bombs doing even more damage per bomb than bombards. Also while naval bombs being not really all that expensive for how powerful they are, even surpassing diamond bombs. All of this makes most of the bombards obsolete. So here are my ideas on how to fix these issues:

-Have a short cooldown for throwing bombs with your hand, similar to ender pearls.
-Reduced range for throwing bombs with your hand. Bombs are heavy, so it wouldn't make sense for an average guy to throw a bomb nearly 50 blocks, I think 20 or so blocks of range should be fine.
-Naval Mines should utilize a block of prismarine instead of a prismarine shard. Shards are far too easy to get large amounts of once an ocean monument is discovered, which usually doesn't take too long.
-Reduced explosion power and damage for naval mines, making them on par with diamond bombs or even slightly weaker.

**Comment by MoriyaShiine** [comment]
Bombs have had a cooldown for a while now upon use, so they are now balanced in that regard
