### ISSUE TITLE
Firecrackers

### ISSUE THREAD

**Issue by PsychoBreadstick** [Ladysnake/BLAST#27]
So I was thinking about having an early game or somewhat early game bomb being introduced into the mod. So what about firecracker strips? They're a real life explosive mostly used for celebrations and entertainment mostly in asian countries, but it could be a pretty interesting weapon in how I think it could work.

Firecracker Strips would first act like normal bombs, being thrown and then having a short countdown before going off. Once it goes off, it will produce a sequence of small and weak, but fiery explosions as it lays there. These small explosions won't break blocks, but may set stuff on fire in a small area as well as damage enemies on or near the exploding firecrackers. It could be pretty useful for dealing decent damage if you can keep an enemy in a general spot for a while, while also creating quite the show.

Here's a sort of recipe to make it (with the tnt representing the firecracker strips). With this recipe providing 8 of them. Making it not all that difficult to get early game if you want something a little cheaper than standard bombs.
![image](https://user-images.githubusercontent.com/90256061/146648479-592ba3cb-f22e-42ec-8caa-570d9f925c40.png)

**Comment by MoriyaShiine** [comment]
I talked with RAT and he said that pipe bombs are a sufficient firecracker alternative
