### ISSUE TITLE
Curseforge Download Issue

### ISSUE THREAD

**Issue by DDriggs00** [Ladysnake/BLAST#32]
Something is preventing this mod from being downloaded as a part of a modpack on third-party launchers. This is typically caused by a misconfigured setting in Curseforge.

**Comment by Eman-3600** [comment]
I think this is intentional behavior, but I'm not quite sure. I'd say rat or pyrofab need to create an faq. This problem has been brought up by so many people without much response that one of them needs to clarify if this is intentional or not.

**Comment by DDriggs00** [comment]
> I think this is intentional behavior

I was giving them the benefit of the doubt.

**Comment by DDriggs00** [comment]
Also, here's a more detailed appeal written by someone with a bit more experience than me: https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

**Comment by Pyrofab** [comment]
Closing this as the mod is now available on modrinth: https://modrinth.com/mod/blast/
