### ISSUE TITLE
FTB Chunks + BLAST

### ISSUE THREAD

**Issue by NordicGamerFE** [Ladysnake/BLAST#34]
You can use the pearl bomb in ftb claims, I have not checked the other bombs. I would like to report this to them directly but they seem to have no way to

Playing: all of fabric 5 1.5.1

**Comment by Kkevsterrr** [comment]
Also having this issue^ Any way to make the bombs respect the claimed chunks that do not permit explosions?

**Comment by WyFryMU** [comment]
Having same issue on All of Fabric 6

Also having issue on Prominence with bypassing openpac claims (similar claiming mod to ftb chunks)

**Comment by EvieTheOwl** [comment]
Added support for mods using the common protections API #43 . I don't think FTB claims includes this but u can use [Cadmus](https://modrinth.com/mod/cadmus) instead
