### ISSUE TITLE
Crashing on Quilt 1.20 server.

### ISSUE THREAD

**Issue by GavinGoGaming** [Ladysnake/BLAST#40]
Here are my logs: https://hastebin.com/share/gevayuziso.bash
if you need any more info/logs i can provide them

**Comment by UpcraftLP** [comment]
BLAST is only updated to 1.19.2, so this is to be expected.

**Comment by GavinGoGaming** [comment]
ah, alright.

**Comment by EvieTheOwl** [comment]
Now updated to 1.20 https://modrinth.com/mod/blast
