### ISSUE TITLE
bones burrier bug

### ISSUE THREAD

**Issue by blobmc** [Ladysnake/BLAST#42]
(sorry for bad english im dutch)
when you place two bonesburriers next to eachother with a remote detonator like this:
![2023-10-20_10 18 37](https://github.com/Ladysnake/BLAST/assets/147933153/bc458a3d-95cb-4d23-80c4-10a2b810db28)
it can go on infinitly and i tried with flint and steel but then it does not happen

**Comment by MoriyaShiine** [comment]
No longer an issue as of 1.13-1.21.1 (specifically tested this exact setup)
