### ISSUE TITLE
Pipebomb Missing Feature

### ISSUE THREAD

**Issue by unluckytokyo** [Ladysnake/BLAST#48]
pipebombs need more functionality

**Comment by Pyrofab** [comment]
Could you be a bit more specific ?

**Comment by unluckytokyo** [comment]
In Explosive Ideas, RAT showcases that when pipebombs are put in a bundle, it displays a few random items inside to "mask" the pipebomb. When the player opens the bundle, the pipebomb ticks and explodes. It also appears that CSMP has a exclusive version of BLAST with those pipebombs, 

Pipebombs can be customized and crafted using an assortment of fireworks, rather than using the base minecraft explosion. 

RAT in a VOD saying something about pipebombs should not explode by default:
https://www.youtube.com/watch?v=0iFVatax13U&t=4889s
1:15:30 - 1:16:50

Explosive Ideas Video:
https://www.youtube.com/watch?v=wLPfat-9_nI&t=425s
6:02 to 7:15

hopefully this provides enough context!!

**Comment by Pyrofab** [comment]
Fixed in https://github.com/Ladysnake/BLAST/commit/b1aedd243d3baf36799757171cd89519e33d282b

**Comment by NolanHewitt** [comment]
On 1.20.1 it seems this functionality is missing. Pipebombs are in the game but have no recipe and when given in creative mode don't have those functionalities.
